Repository TEAM-MUJAE/Face_AI_Model_Service_BE, pull requests merged in 2024-03, with the labels that each got.

#8 20240308 로그인, 회원가입, 정보수정 구조 설정
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/mujae/MujaeBeApplication.java
  src/main/java/com/mujae/member/controller/HomeController.java
  src/main/java/com/mujae/member/controller/MemberController.java
  src/main/java/com/mujae/member/dao/MemberDAO.java
  src/main/java/com/mujae/member/dto/MemberDTO.java
  src/main/java/com/mujae/member/mapper/MemberMapper.xml
  src/main/java/com/mujae/member/service/MemberService.java
  src/main/java/com/mujae/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mybatisConfig/Mybatis-Config.xml
  src/main/resources/static/jquery/jquery-3.7.0.min.js
  src/main/resources/static/script/commonScript.js
  src/main/resources/static/script/member.js
  src/main/webapp/WEB-INF/view/Info.jsp
  src/main/webapp/WEB-INF/view/Login.jsp
  src/main/webapp/WEB-INF/view/Main.jsp
  src/main/webapp/WEB-INF/view/MsgPage.jsp
  src/main/webapp/WEB-INF/view/Register.jsp
  src/main/webapp/WEB-INF/view/Top.jsp
  src/main/webapp/WEB-INF/view/Update.jsp
  src/test/java/com/mujae/MujaeBeApplicationTests.java
Labels: good first issue

#12 20240314 mapper, DTO 수정
  src/main/java/com/mujae/member/dao/MemberDAO.java
  src/main/java/com/mujae/member/dto/MemberDTO.java
  src/main/java/com/mujae/member/mapper/MemberMapper.xml
Labels: enhancement

#13 20240315 service, Mybatis 수정
  src/main/java/com/mujae/member/mapper/MemberMapper.xml
  src/main/java/com/mujae/member/service/MemberService.java
  src/main/java/com/mujae/member/service/MemberServiceImpl.java
  src/main/resources/mybatisConfig/Mybatis-Config.xml
Labels: enhancement

#14 20240315 mybatis 오류로 인한 프로젝트 리팩토링
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  src/main/java/com/mujae/Application.java
  src/main/java/com/mujae/MujaeBeApplication.java
  src/main/java/com/mujae/config/MyBatisConfig.java
  src/main/java/com/mujae/member/controller/MemberController.java
  src/main/java/com/mujae/member/dao/MemberMapper.java
  src/main/java/com/mujae/member/mapper/MemberMapper.xml
  src/main/java/com/mujae/member/service/MemberService.java
  src/main/java/com/mujae/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mybatisConfig/Mybatis-Config.xml
  src/main/resources/static/jquery/jquery-3.7.0.min.js
  src/main/resources/static/script/commonScript.js
  src/main/resources/static/script/member.js
  src/main/webapp/WEB-INF/view/Info.jsp
  src/main/webapp/WEB-INF/view/Login.jsp
  src/main/webapp/WEB-INF/view/Main.jsp
  src/main/webapp/WEB-INF/view/MsgPage.jsp
  src/main/webapp/WEB-INF/view/Register.jsp
  src/main/webapp/WEB-INF/view/Top.jsp
  src/main/webapp/WEB-INF/view/Update.jsp
  src/test/java/com/mujae/ApplicationTests.java
Labels: bug, enhancement

#15 20240318 로그인, 회원가입 기능 추가
  src/main/java/com/mujae/member/controller/MemberController.java
  src/main/java/com/mujae/member/dao/MemberMapper.java
  src/main/java/com/mujae/member/dto/MemberDTO.java
  src/main/java/com/mujae/member/service/MemberService.java
  src/main/java/com/mujae/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/MemberMapper.xml
Labels: enhancement

#17 20240321 회원가입, 정보수정 예외처리 기능 추가
  src/main/java/com/mujae/member/controller/MemberController.java
  src/main/java/com/mujae/member/service/MemberServiceImpl.java
Labels: enhancement

#19 20240322 백엔드 릴리즈 v1.0.0
  .gitignore
  Dockerfile
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/mujae/Application.java
  src/main/java/com/mujae/config/MyBatisConfig.java
  src/main/java/com/mujae/member/controller/HomeController.java
  src/main/java/com/mujae/member/controller/JoinResponse.java
  src/main/java/com/mujae/member/controller/MemberController.java
  src/main/java/com/mujae/member/dao/MemberMapper.java
  src/main/java/com/mujae/member/dto/MemberDTO.java
  src/main/java/com/mujae/member/service/MemberService.java
  src/main/java/com/mujae/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mybatisConfig/Mybatis-Config.xml
  src/test/java/com/mujae/ApplicationTests.java
Labels: good first issue
